# Quiz FastAPI

## Pregunta 1

¿Cuál es el propósito principal de FastAPI?

- [ ] Crear aplicaciones web rápidas y eficientes.
- [ ] Facilitar el desarrollo de APIs RESTful.
- [ ] Ambas opciones anteriores.

## Pregunta 2

Cuál de las siguientes afirmaciones sobre FastAPI es correcta?

- [ ] FastAPI es un framework basado en Flask.
- [ ] FastAPI utiliza el lenguaje de programación Java.
- [ ] FastAPI es compatible con Python 3.7 y versiones posteriores.

## Pregunta 3

Cuál de las siguientes características es una ventaja de FastAPI?

- [ ] Soporte para tipos de datos estáticos.
- [ ] Generación automática de documentación interactiva.
- [ ] Ambas opciones anteriores.

## Pregunta 4

Cuál de las siguientes afirmaciones sobre FastAPI es incorrecta?

- [ ] FastAPI es un framework asincrónico.
- [ ] FastAPI es compatible con bases de datos SQL y NoSQL.
- [ ] FastAPI no es adecuado para aplicaciones de alto rendimiento.

## Pregunta 5

¿Cuál es el comando correcto para instalar FastAPI?

- [ ] pip install fastapi
- [ ] pip install fastapi uvicorn
- [ ] pip install fastapi[all]

<details>
<summary>Respuestas</summary>

1. Ambas opciones anteriores.
2. FastAPI es compatible con Python 3.7 y versiones posteriores.
3. Ambas opciones anteriores.
4. FastAPI no es adecuado para aplicaciones de alto rendimiento.
5. **pip install fastapi uvicorn**

</details>