# API Restful con FastAPI

Para crear un API Restful con FastAPI, empezamos creando el directorio **app** y dentro de este directorio creamos el archivo **main.py** con el siguiente contenido:

```python
from fastapi import FastAPI

app = FastAPI()

@app.get("/")
def read_root():
    return {"Hello": "World"}
```

En el directorio **app**, ejecutamos el siguiente comando para iniciar el servidor de FastAPI:

```bash
uvicorn main:app --reload
```

Para probar el API Restful, simplemente abrimos nuestro navegador y navegamos a la siguiente URL: <http://127.0.0.1:8000> y veremos el siguiente resultado:

```json
{"Hello": "World"}
```

Para probar la documentación interactiva de FastAPI, simplemente abrimos nuestro navegador y navegamos a la siguiente URL: <http://127.0.0.1:8000/docs> o <http://127.0.0.1:8000/redoc> y veremos la documentación de nuestro API.

Para más información sobre FastAPI, visita la [documentación oficial de FastAPI](https://fastapi.tiangolo.com/).

# ¿Qué sigue?

En la siguiente lección, aprenderemos cómo crear una API RESTful con FastAPI.

[Prueba tu conocimiento](2_api_restfull_quiz.qmd)
