# Quiz FastAPI

## Pregunta 1

¿Qué devuelve el servidor de uvicorn?

- [ ] Un mensaje de error.
- [ ] Un mensaje de advertencia.
- [ ] Un mensaje de éxito.
- [ ] Un mensaje de información.

## Pregunta 2

¿Para qué me sirve un json en FASTAPI?

- [ ] Para crear una API RESTful.
- [ ] Para crear una API SOAP.
- [ ] Para crear una API GraphQL.
- [ ] Para crear una API RESTful y una API SOAP.

## Pregunta 3

¿Como ejecuto un servidor de FastAPI?

- [ ] uvicorn main:app --reload
- [ ] uvicorn main:app --no-reload
- [ ] uvicorn main:app --reload --port 8000
- [ ] uvicorn main:app --reload --port 8000 --host

## Pregunta 4

¿Por qué debo instalar uvicorn?

- [ ] Para ejecutar FastAPI.
- [ ] Para ejecutar Flask.
- [ ] Para ejecutar Django.
- [ ] Para ejecutar FastAPI y Flask.

## Pregunta 5

¿Qué comando debo ejecutar para instalar FastAPI y uvicorn?

- [ ] pip install fastapi
- [ ] pip install uvicorn
- [ ] pip install fastapi uvicorn
- [ ] pip install fastapi[all]

<details>
<summary>Respuestas</summary>

1. Un mensaje de éxito.
2. Para crear una API RESTful.
3. uvicorn main:app --reload
4. Para ejecutar FastAPI.
5. pip install fastapi uvicorn

</details>